package basic.java.demo.project.SwitchCase;

public class StringSwitchCaseJava7 {

    // Here the Strings in Case statement are converted into its hashCode value
    // "FB80".hashCode() is 2150580
    // case 2150580:
    // if(!s.equals("FB80")) {
    // break;
    // }
    // System.out.println("Switch Case"); break label0;

    // IF two Strings has same hashCode. "FB" and "Ea" has the hashCode(2236)
    // case 2236:
    // if(!s.equals("FB")) // {
    //    if(s.equals("Ea")) {
    //        System.out.println("Switch Case Ea"); break label0;
    //     }
    // } else {
    //    System.out.println("Switch Case FB"); break label0;
    // }
    // break;
    public static void main(String[] args) {
        
        String switchKey = "FB";
        switch (switchKey) {
        case "FB":
            System.out.println("Switch Case FB");
            break;
        case "Ea":
            System.out.println("Switch Case Ea");
            break;
        case "FB0": System.out.println("Switch Case"); break;
        case "FB1": System.out.println("Switch Case"); break;
        case "FB2": System.out.println("Switch Case"); break;
        case "FB3": System.out.println("Switch Case"); break;
        case "FB4": System.out.println("Switch Case"); break;
        case "FB5": System.out.println("Switch Case"); break;
        case "FB6": System.out.println("Switch Case"); break;
        case "FB7": System.out.println("Switch Case"); break;
        case "FB8": System.out.println("Switch Case"); break;
        case "FB9": System.out.println("Switch Case"); break;
        case "FB10": System.out.println("Switch Case"); break;
        case "FB11": System.out.println("Switch Case"); break;
        case "FB12": System.out.println("Switch Case"); break;
        case "FB13": System.out.println("Switch Case"); break;
        case "FB14": System.out.println("Switch Case"); break;
        case "FB15": System.out.println("Switch Case"); break;
        case "FB16": System.out.println("Switch Case"); break;
        case "FB17": System.out.println("Switch Case"); break;
        case "FB18": System.out.println("Switch Case"); break;
        case "FB19": System.out.println("Switch Case"); break;
        case "FB20": System.out.println("Switch Case"); break;
        case "FB21": System.out.println("Switch Case"); break;
        case "FB22": System.out.println("Switch Case"); break;
        case "FB23": System.out.println("Switch Case"); break;
        case "FB24": System.out.println("Switch Case"); break;
        case "FB25": System.out.println("Switch Case"); break;
        case "FB26": System.out.println("Switch Case"); break;
        case "FB27": System.out.println("Switch Case"); break;
        case "FB28": System.out.println("Switch Case"); break;
        case "FB29": System.out.println("Switch Case"); break;
        case "FB30": System.out.println("Switch Case"); break;
        case "FB31": System.out.println("Switch Case"); break;
        case "FB32": System.out.println("Switch Case"); break;
        case "FB33": System.out.println("Switch Case"); break;
        case "FB34": System.out.println("Switch Case"); break;
        case "FB35": System.out.println("Switch Case"); break;
        case "FB36": System.out.println("Switch Case"); break;
        case "FB37": System.out.println("Switch Case"); break;
        case "FB38": System.out.println("Switch Case"); break;
        case "FB39": System.out.println("Switch Case"); break;
        case "FB40": System.out.println("Switch Case"); break;
        case "FB41": System.out.println("Switch Case"); break;
        case "FB42": System.out.println("Switch Case"); break;
        case "FB43": System.out.println("Switch Case"); break;
        case "FB44": System.out.println("Switch Case"); break;
        case "FB45": System.out.println("Switch Case"); break;
        case "FB46": System.out.println("Switch Case"); break;
        case "FB47": System.out.println("Switch Case"); break;
        case "FB48": System.out.println("Switch Case"); break;
        case "FB49": System.out.println("Switch Case"); break;
        case "FB50": System.out.println("Switch Case"); break;
        case "FB51": System.out.println("Switch Case"); break;
        case "FB52": System.out.println("Switch Case"); break;
        case "FB53": System.out.println("Switch Case"); break;
        case "FB54": System.out.println("Switch Case"); break;
        case "FB55": System.out.println("Switch Case"); break;
        case "FB56": System.out.println("Switch Case"); break;
        case "FB57": System.out.println("Switch Case"); break;
        case "FB58": System.out.println("Switch Case"); break;
        case "FB59": System.out.println("Switch Case"); break;
        case "FB60": System.out.println("Switch Case"); break;
        case "FB61": System.out.println("Switch Case"); break;
        case "FB62": System.out.println("Switch Case"); break;
        case "FB63": System.out.println("Switch Case"); break;
        case "FB64": System.out.println("Switch Case"); break;
        case "FB65": System.out.println("Switch Case"); break;
        case "FB66": System.out.println("Switch Case"); break;
        case "FB67": System.out.println("Switch Case"); break;
        case "FB68": System.out.println("Switch Case"); break;
        case "FB69": System.out.println("Switch Case"); break;
        case "FB70": System.out.println("Switch Case"); break;
        case "FB71": System.out.println("Switch Case"); break;
        case "FB72": System.out.println("Switch Case"); break;
        case "FB73": System.out.println("Switch Case"); break;
        case "FB74": System.out.println("Switch Case"); break;
        case "FB75": System.out.println("Switch Case"); break;
        case "FB76": System.out.println("Switch Case"); break;
        case "FB77": System.out.println("Switch Case"); break;
        case "FB78": System.out.println("Switch Case"); break;
        case "FB79": System.out.println("Switch Case"); break;
        case "FB80": System.out.println("Switch Case"); break;
        case "FB81": System.out.println("Switch Case"); break;
        case "FB82": System.out.println("Switch Case"); break;
        case "FB83": System.out.println("Switch Case"); break;
        case "FB84": System.out.println("Switch Case"); break;
        case "FB85": System.out.println("Switch Case"); break;
        case "FB86": System.out.println("Switch Case"); break;
        case "FB87": System.out.println("Switch Case"); break;
        case "FB88": System.out.println("Switch Case"); break;
        case "FB89": System.out.println("Switch Case"); break;
        case "FB90": System.out.println("Switch Case"); break;
        case "FB91": System.out.println("Switch Case"); break;
        case "FB92": System.out.println("Switch Case"); break;
        case "FB93": System.out.println("Switch Case"); break;
        case "FB94": System.out.println("Switch Case"); break;
        case "FB95": System.out.println("Switch Case"); break;
        case "FB96": System.out.println("Switch Case"); break;
        case "FB97": System.out.println("Switch Case"); break;
        case "FB98": System.out.println("Switch Case"); break;
        case "FB99": System.out.println("Switch Case"); break;
        case "FB100": System.out.println("Switch Case"); break;
        case "FB101": System.out.println("Switch Case"); break;
        case "FB102": System.out.println("Switch Case"); break;
        case "FB103": System.out.println("Switch Case"); break;
        case "FB104": System.out.println("Switch Case"); break;
        case "FB105": System.out.println("Switch Case"); break;
        case "FB106": System.out.println("Switch Case"); break;
        case "FB107": System.out.println("Switch Case"); break;
        case "FB108": System.out.println("Switch Case"); break;
        case "FB109": System.out.println("Switch Case"); break;
        case "FB110": System.out.println("Switch Case"); break;
        case "FB111": System.out.println("Switch Case"); break;
        case "FB112": System.out.println("Switch Case"); break;
        case "FB113": System.out.println("Switch Case"); break;
        case "FB114": System.out.println("Switch Case"); break;
        case "FB115": System.out.println("Switch Case"); break;
        case "FB116": System.out.println("Switch Case"); break;
        case "FB117": System.out.println("Switch Case"); break;
        case "FB118": System.out.println("Switch Case"); break;
        case "FB119": System.out.println("Switch Case"); break;
        case "FB120": System.out.println("Switch Case"); break;
        case "FB121": System.out.println("Switch Case"); break;
        case "FB122": System.out.println("Switch Case"); break;
        case "FB123": System.out.println("Switch Case"); break;
        case "FB124": System.out.println("Switch Case"); break;
        case "FB125": System.out.println("Switch Case"); break;
        case "FB126": System.out.println("Switch Case"); break;
        case "FB127": System.out.println("Switch Case"); break;
        case "FB128": System.out.println("Switch Case"); break;
        case "FB129": System.out.println("Switch Case"); break;
        case "FB130": System.out.println("Switch Case"); break;
        case "FB131": System.out.println("Switch Case"); break;
        case "FB132": System.out.println("Switch Case"); break;
        case "FB133": System.out.println("Switch Case"); break;
        case "FB134": System.out.println("Switch Case"); break;
        case "FB135": System.out.println("Switch Case"); break;
        case "FB136": System.out.println("Switch Case"); break;
        case "FB137": System.out.println("Switch Case"); break;
        case "FB138": System.out.println("Switch Case"); break;
        case "FB139": System.out.println("Switch Case"); break;
        case "FB140": System.out.println("Switch Case"); break;
        case "FB141": System.out.println("Switch Case"); break;
        case "FB142": System.out.println("Switch Case"); break;
        case "FB143": System.out.println("Switch Case"); break;
        case "FB144": System.out.println("Switch Case"); break;
        case "FB145": System.out.println("Switch Case"); break;
        case "FB146": System.out.println("Switch Case"); break;
        case "FB147": System.out.println("Switch Case"); break;
        case "FB148": System.out.println("Switch Case"); break;
        case "FB149": System.out.println("Switch Case"); break;
        case "FB150": System.out.println("Switch Case"); break;
        case "FB151": System.out.println("Switch Case"); break;
        case "FB152": System.out.println("Switch Case"); break;
        case "FB153": System.out.println("Switch Case"); break;
        case "FB154": System.out.println("Switch Case"); break;
        case "FB155": System.out.println("Switch Case"); break;
        case "FB156": System.out.println("Switch Case"); break;
        case "FB157": System.out.println("Switch Case"); break;
        case "FB158": System.out.println("Switch Case"); break;
        case "FB159": System.out.println("Switch Case"); break;
        case "FB160": System.out.println("Switch Case"); break;
        case "FB161": System.out.println("Switch Case"); break;
        case "FB162": System.out.println("Switch Case"); break;
        case "FB163": System.out.println("Switch Case"); break;
        case "FB164": System.out.println("Switch Case"); break;
        case "FB165": System.out.println("Switch Case"); break;
        case "FB166": System.out.println("Switch Case"); break;
        case "FB167": System.out.println("Switch Case"); break;
        case "FB168": System.out.println("Switch Case"); break;
        case "FB169": System.out.println("Switch Case"); break;
        case "FB170": System.out.println("Switch Case"); break;
        case "FB171": System.out.println("Switch Case"); break;
        case "FB172": System.out.println("Switch Case"); break;
        case "FB173": System.out.println("Switch Case"); break;
        case "FB174": System.out.println("Switch Case"); break;
        case "FB175": System.out.println("Switch Case"); break;
        case "FB176": System.out.println("Switch Case"); break;
        case "FB177": System.out.println("Switch Case"); break;
        case "FB178": System.out.println("Switch Case"); break;
        case "FB179": System.out.println("Switch Case"); break;
        case "FB180": System.out.println("Switch Case"); break;
        case "FB181": System.out.println("Switch Case"); break;
        case "FB182": System.out.println("Switch Case"); break;
        case "FB183": System.out.println("Switch Case"); break;
        case "FB184": System.out.println("Switch Case"); break;
        case "FB185": System.out.println("Switch Case"); break;
        case "FB186": System.out.println("Switch Case"); break;
        case "FB187": System.out.println("Switch Case"); break;
        case "FB188": System.out.println("Switch Case"); break;
        case "FB189": System.out.println("Switch Case"); break;
        case "FB190": System.out.println("Switch Case"); break;
        case "FB191": System.out.println("Switch Case"); break;
        case "FB192": System.out.println("Switch Case"); break;
        case "FB193": System.out.println("Switch Case"); break;
        case "FB194": System.out.println("Switch Case"); break;
        case "FB195": System.out.println("Switch Case"); break;
        case "FB196": System.out.println("Switch Case"); break;
        case "FB197": System.out.println("Switch Case"); break;
        case "FB198": System.out.println("Switch Case"); break;
        case "FB199": System.out.println("Switch Case"); break;
        case "FB200": System.out.println("Switch Case"); break;
        case "FB201": System.out.println("Switch Case"); break;
        case "FB202": System.out.println("Switch Case"); break;
        case "FB203": System.out.println("Switch Case"); break;
        case "FB204": System.out.println("Switch Case"); break;
        case "FB205": System.out.println("Switch Case"); break;
        case "FB206": System.out.println("Switch Case"); break;
        case "FB207": System.out.println("Switch Case"); break;
        case "FB208": System.out.println("Switch Case"); break;
        case "FB209": System.out.println("Switch Case"); break;
        case "FB210": System.out.println("Switch Case"); break;
        case "FB211": System.out.println("Switch Case"); break;
        case "FB212": System.out.println("Switch Case"); break;
        case "FB213": System.out.println("Switch Case"); break;
        case "FB214": System.out.println("Switch Case"); break;
        case "FB215": System.out.println("Switch Case"); break;
        case "FB216": System.out.println("Switch Case"); break;
        case "FB217": System.out.println("Switch Case"); break;
        case "FB218": System.out.println("Switch Case"); break;
        case "FB219": System.out.println("Switch Case"); break;
        case "FB220": System.out.println("Switch Case"); break;
        case "FB221": System.out.println("Switch Case"); break;
        case "FB222": System.out.println("Switch Case"); break;
        case "FB223": System.out.println("Switch Case"); break;
        case "FB224": System.out.println("Switch Case"); break;
        case "FB225": System.out.println("Switch Case"); break;
        case "FB226": System.out.println("Switch Case"); break;
        case "FB227": System.out.println("Switch Case"); break;
        case "FB228": System.out.println("Switch Case"); break;
        case "FB229": System.out.println("Switch Case"); break;
        case "FB230": System.out.println("Switch Case"); break;
        case "FB231": System.out.println("Switch Case"); break;
        case "FB232": System.out.println("Switch Case"); break;
        case "FB233": System.out.println("Switch Case"); break;
        case "FB234": System.out.println("Switch Case"); break;
        case "FB235": System.out.println("Switch Case"); break;
        case "FB236": System.out.println("Switch Case"); break;
        case "FB237": System.out.println("Switch Case"); break;
        case "FB238": System.out.println("Switch Case"); break;
        case "FB239": System.out.println("Switch Case"); break;
        case "FB240": System.out.println("Switch Case"); break;
        case "FB241": System.out.println("Switch Case"); break;
        case "FB242": System.out.println("Switch Case"); break;
        case "FB243": System.out.println("Switch Case"); break;
        case "FB244": System.out.println("Switch Case"); break;
        case "FB245": System.out.println("Switch Case"); break;
        case "FB246": System.out.println("Switch Case"); break;
        case "FB247": System.out.println("Switch Case"); break;
        case "FB248": System.out.println("Switch Case"); break;
        case "FB249": System.out.println("Switch Case"); break;
        case "FB250": System.out.println("Switch Case"); break;
        case "FB251": System.out.println("Switch Case"); break;
        case "FB252": System.out.println("Switch Case"); break;
        case "FB253": System.out.println("Switch Case"); break;
        case "FB254": System.out.println("Switch Case"); break;
        case "FB255": System.out.println("Switch Case"); break;
        case "FB256": System.out.println("Switch Case"); break;
        case "FB257": System.out.println("Switch Case"); break;
        case "FB258": System.out.println("Switch Case"); break;
        case "FB259": System.out.println("Switch Case"); break;
        case "FB260": System.out.println("Switch Case"); break;
        case "FB261": System.out.println("Switch Case"); break;
        case "FB262": System.out.println("Switch Case"); break;
        case "FB263": System.out.println("Switch Case"); break;
        case "FB264": System.out.println("Switch Case"); break;
        case "FB265": System.out.println("Switch Case"); break;
        case "FB266": System.out.println("Switch Case"); break;
        case "FB267": System.out.println("Switch Case"); break;
        case "FB268": System.out.println("Switch Case"); break;
        case "FB269": System.out.println("Switch Case"); break;
        case "FB270": System.out.println("Switch Case"); break;
        case "FB271": System.out.println("Switch Case"); break;
        case "FB272": System.out.println("Switch Case"); break;
        case "FB273": System.out.println("Switch Case"); break;
        case "FB274": System.out.println("Switch Case"); break;
        case "FB275": System.out.println("Switch Case"); break;
        case "FB276": System.out.println("Switch Case"); break;
        case "FB277": System.out.println("Switch Case"); break;
        case "FB278": System.out.println("Switch Case"); break;
        case "FB279": System.out.println("Switch Case"); break;
        case "FB280": System.out.println("Switch Case"); break;
        case "FB281": System.out.println("Switch Case"); break;
        case "FB282": System.out.println("Switch Case"); break;
        case "FB283": System.out.println("Switch Case"); break;
        case "FB284": System.out.println("Switch Case"); break;
        case "FB285": System.out.println("Switch Case"); break;
        case "FB286": System.out.println("Switch Case"); break;
        case "FB287": System.out.println("Switch Case"); break;
        case "FB288": System.out.println("Switch Case"); break;
        case "FB289": System.out.println("Switch Case"); break;
        case "FB290": System.out.println("Switch Case"); break;
        case "FB291": System.out.println("Switch Case"); break;
        case "FB292": System.out.println("Switch Case"); break;
        case "FB293": System.out.println("Switch Case"); break;
        case "FB294": System.out.println("Switch Case"); break;
        case "FB295": System.out.println("Switch Case"); break;
        case "FB296": System.out.println("Switch Case"); break;
        case "FB297": System.out.println("Switch Case"); break;
        case "FB298": System.out.println("Switch Case"); break;
        case "FB299": System.out.println("Switch Case"); break;
        case "FB300": System.out.println("Switch Case"); break;
            
        default:
            System.out.println("Default Case");
            break;
        }
        
        for(int i=0; i<=300 ; i++){
            System.out.println("case \"FB" + i + "\"" + ": System.out.println(\"Switch Case\"); break;");
        }
        System.out.println("FB13".hashCode());
    }
}
